// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgvW-UlgVwcfZQadWrZ2aIKy59cKUz2RQ',
    appId: '1:664867399245:web:c48184948b8c16500b5e04',
    messagingSenderId: '664867399245',
    projectId: 'animation-b4d9a',
    authDomain: 'animation-b4d9a.firebaseapp.com',
    storageBucket: 'animation-b4d9a.firebasestorage.app',
    measurementId: 'G-TR3R216XFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5fSqpYAj1kvlEaA4Ug_QiP2adJWCzkxQ',
    appId: '1:664867399245:android:0c90afd6f5da5c390b5e04',
    messagingSenderId: '664867399245',
    projectId: 'animation-b4d9a',
    storageBucket: 'animation-b4d9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-2Pw9vowtJzYRVYbenw4t-4-KcdzSKhk',
    appId: '1:664867399245:ios:37ce3f6878987ca10b5e04',
    messagingSenderId: '664867399245',
    projectId: 'animation-b4d9a',
    storageBucket: 'animation-b4d9a.firebasestorage.app',
    iosBundleId: 'com.example.infyappTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-2Pw9vowtJzYRVYbenw4t-4-KcdzSKhk',
    appId: '1:664867399245:ios:37ce3f6878987ca10b5e04',
    messagingSenderId: '664867399245',
    projectId: 'animation-b4d9a',
    storageBucket: 'animation-b4d9a.firebasestorage.app',
    iosBundleId: 'com.example.infyappTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgvW-UlgVwcfZQadWrZ2aIKy59cKUz2RQ',
    appId: '1:664867399245:web:53dc8ded1d046f6c0b5e04',
    messagingSenderId: '664867399245',
    projectId: 'animation-b4d9a',
    authDomain: 'animation-b4d9a.firebaseapp.com',
    storageBucket: 'animation-b4d9a.firebasestorage.app',
    measurementId: 'G-WTCMLW8QC4',
  );
}
